version: 2.1
orbs:
  maven: circleci/maven@1.4.0

executors:
  jdk8:
    docker:
      - image: cimg/openjdk:8.0
  jdk11:
    docker:
      - image: cimg/openjdk:11.0
  jdk17:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build:
    working_directory: /tmp/td-client-java
    parameters:
      jdk:
        type: executor
    executor: << parameters.jdk >>
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Test
                command: mvn test -Dtd.client.endpoint=api-staging.treasuredata.com
      - maven/process_test_results
      - store_artifacts:
            path: /tmp/td-client-java/target/site

workflows:
  build:
    jobs:
      - build:
          # name: build with JDK 11 & 17
          matrix:
            parameters:
              jdk: [jdk8, jdk11, jdk17]
